apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    canary:
      steps:
      - setWeight: 10
        pause: {}
      - setWeight: 20
        pause:
          duration: 10m
      - setWeight: 30
        pause: {}
      - setWeight: 40
        pause:
          duration: 10m
      - setWeight: 50
        pause: {}
      - setWeight: 60
        pause:
          duration: 10m
      - setWeight: 70
        pause: {}
      - setWeight: 80
        pause:
          duration: 10m
      - setWeight: 90
        pause: {}
      - setWeight: 100
        pause: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
